export type RuleErrorCode =
  | 'GAME_NOT_ACTIVE'
  | 'WRONG_PLAYER'
  | 'INVALID_BID'
  | 'BID_NOT_HIGHER'
  | 'INVALID_PLAY'
  | 'CARD_NOT_OWNED'
  | 'CANNOT_BEAT_CURRENT_PLAY'
  | 'CANNOT_PASS_WHEN_LEADING'
  | 'PLAYER_ALREADY_FINISHED';
